name: Publish to Package Registries

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build Package
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 2.1
    - name: Build with dotnet
      run: dotnet build EPPlus.TableSheet --configuration Release
      
    - name: Pack
      run: dotnet pack EPPlus.TableSheet --configuration Release --output ${{ github.workspace }}/artifacts --no-build
    
    - name: Publish Artifact
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: ${{ github.workspace }}/artifacts

  deploy:
    needs: build
    name: Deploy Packages
    runs-on: windows-latest
    
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 2.1

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
	  path: ${{ github.workspace }}/package

      - name: Setup NuGet
        uses: NuGet/setup-nuget@main
        with:
          nuget-api-key: ${{ secrets.NUGETORG_API_KEY }}
          nuget-version: latest

      - name: Push to NuGet
        run: dotnet nuget push ${{ github.workspace }}\package\*.nupkg -k ${{ secrets.NUGETORG_API_KEY }} -s https://nuget.org --skip-duplicate

      - name: Add GitHub Package Registry Source
      	run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name GPR "https://nuget.pkg.github.com/TrueAnalyticsSolutions/index.json"

      - name: Push to GitHub Packages
        run: dotnet nuget push ${{ github.workspace }}\package\*.nupkg -Source "GPR" -SkipDuplicate
